"""CDK emitter — functor from ResourceGraph to CDK constructs.

CT mapping:
  - This is a functor: it maps objects (ResourceNodes) and morphisms
    (ResourceEdges) in our free category to objects (CDK Constructs)
    and morphisms (IAM grants, event subscriptions) in the CDK category.
  - It preserves composition: if A → B → C in the graph, the
    corresponding CDK constructs maintain those relationships.
"""

from __future__ import annotations

import json
from typing import Any

from machete.infra.graph import ResourceGraph, ResourceNode, ResourceType


def emit_cdk_json(graph: ResourceGraph, stack_name: str = "MacheteStack") -> dict[str, Any]:
    """Emit a CloudFormation-compatible JSON template from a ResourceGraph.

    This is a simplified emitter that produces a CDK-synthesizable template
    without requiring aws_cdk to be installed. For full CDK synthesis,
    use emit_cdk_app().

    Returns a dict that can be written as a CloudFormation template.
    """
    resources: dict[str, Any] = {}
    outputs: dict[str, Any] = {}

    for node in graph.nodes.values():
        cfn = _node_to_cloudformation(node)
        if cfn:
            resources[_cfn_logical_id(node.id)] = cfn

    # Add edges as IAM policies and event source mappings
    for edge in graph.edges:
        source = graph.get_node(edge.source)
        target = graph.get_node(edge.target)
        if source and target:
            edge_resources = _edge_to_cloudformation(edge, source, target)
            resources.update(edge_resources)

    # Add outputs for API Gateways
    for node in graph.nodes.values():
        if node.type == ResourceType.API_GATEWAY:
            lid = _cfn_logical_id(node.id)
            outputs[f"{lid}Url"] = {
                "Value": {
                    "Fn::Sub": f"https://${{{lid}}}.execute-api.${{AWS::Region}}.amazonaws.com/prod"
                },
                "Description": f"URL for {node.name}",
            }

    return {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": f"Machete-generated stack: {stack_name}",
        "Resources": resources,
        "Outputs": outputs,
    }


def emit_cdk_app(graph: ResourceGraph, stack_name: str = "MacheteStack") -> str:
    """Emit a CDK app Python file that can be run with `cdk synth`.

    Returns the Python source code for a CDK app.
    """
    lines = [
        "#!/usr/bin/env python3",
        '"""Auto-generated by Agente Machete — Infrastructure From Code."""',
        "",
        "import aws_cdk as cdk",
        "from aws_cdk import (",
        "    Stack,",
        "    aws_lambda as _lambda,",
        "    aws_apigateway as apigw,",
        "    aws_sqs as sqs,",
        "    aws_dynamodb as dynamodb,",
        "    aws_events as events,",
        "    aws_events_targets as targets,",
        "    aws_iam as iam,",
        "    aws_lambda_event_sources as event_sources,",
        "    Duration,",
        "    RemovalPolicy,",
        ")",
        "from constructs import Construct",
        "",
        "",
        f"class {_class_name(stack_name)}(Stack):",
        "    def __init__(self, scope: Construct, id: str, **kwargs) -> None:",
        "        super().__init__(scope, id, **kwargs)",
        "",
    ]

    # Emit Lambda functions
    for node in graph.nodes.values():
        if node.type == ResourceType.LAMBDA:
            lines.extend(_emit_lambda(node))
            lines.append("")

    # Emit API Gateways
    for node in graph.nodes.values():
        if node.type == ResourceType.API_GATEWAY:
            lines.extend(_emit_api_gateway(node, graph))
            lines.append("")

    # Emit SQS queues
    for node in graph.nodes.values():
        if node.type == ResourceType.SQS:
            lines.extend(_emit_sqs(node, graph))
            lines.append("")

    # Emit EventBridge rules
    for node in graph.nodes.values():
        if node.type == ResourceType.EVENTBRIDGE:
            lines.extend(_emit_eventbridge(node, graph))
            lines.append("")

    # App boilerplate
    lines.extend(
        [
            "",
            "app = cdk.App()",
            f'{_class_name(stack_name)}(app, "{stack_name}")',
            "app.synth()",
        ]
    )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CloudFormation resource mappers
# ---------------------------------------------------------------------------


def _node_to_cloudformation(node: ResourceNode) -> dict[str, Any] | None:
    match node.type:
        case ResourceType.LAMBDA:
            return {
                "Type": "AWS::Lambda::Function",
                "Properties": {
                    "FunctionName": node.name,
                    "Handler": node.properties.get("handler", "index.handler"),
                    "Runtime": node.properties.get("runtime", "python3.11"),
                    "Timeout": node.properties.get("timeout", 60),
                    "MemorySize": node.properties.get("memory", 256),
                    "Environment": {
                        "Variables": node.properties.get("environment", {}),
                    },
                    "Code": {"ZipFile": "# Placeholder — deploy with machete deploy"},
                },
            }
        case ResourceType.API_GATEWAY:
            return {
                "Type": "AWS::ApiGateway::RestApi",
                "Properties": {
                    "Name": node.name,
                    "Description": node.properties.get("description", ""),
                },
            }
        case ResourceType.SQS:
            return {
                "Type": "AWS::SQS::Queue",
                "Properties": {
                    "QueueName": node.name,
                    "VisibilityTimeout": node.properties.get("visibility_timeout", 30),
                },
            }
        case ResourceType.EVENTBRIDGE:
            schedule = node.properties.get("schedule_expression", "rate(1 hour)")
            return {
                "Type": "AWS::Events::Rule",
                "Properties": {
                    "Name": node.name,
                    "ScheduleExpression": schedule,
                    "State": "ENABLED",
                },
            }
        case ResourceType.IAM_ROLE:
            return {
                "Type": "AWS::IAM::Role",
                "Properties": {
                    "RoleName": node.name,
                    "AssumeRolePolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Principal": {
                                    "Service": node.properties.get(
                                        "assume_role_service", "lambda.amazonaws.com"
                                    )
                                },
                                "Action": "sts:AssumeRole",
                            }
                        ],
                    },
                },
            }
        case _:
            return None


def _edge_to_cloudformation(
    edge: Any, source: ResourceNode, target: ResourceNode
) -> dict[str, Any]:
    """Convert edges to IAM policies or event source mappings."""
    return {}  # Simplified — full version adds inline policies


def _cfn_logical_id(node_id: str) -> str:
    """Convert a node ID to a CloudFormation logical ID."""
    return "".join(part.capitalize() for part in node_id.replace("-", " ").split())


def _class_name(stack_name: str) -> str:
    # Split on non-alpha boundaries, preserving existing CamelCase
    import re

    parts = re.split(r"[-_ ]+", stack_name)
    return "".join(p[0].upper() + p[1:] if p else "" for p in parts)


# ---------------------------------------------------------------------------
# CDK construct emitters (for emit_cdk_app)
# ---------------------------------------------------------------------------


def _emit_lambda(node: ResourceNode) -> list[str]:
    var = _var_name(node.id)
    props = node.properties
    env_str = json.dumps(props.get("environment", {}))
    return [
        f"        self.{var} = _lambda.Function(",
        f"            self, '{node.id}',",
        f"            function_name='{node.name}',",
        f"            handler='{props.get('handler', 'index.handler')}',",
        "            runtime=_lambda.Runtime.PYTHON_3_11,",
        f"            timeout=Duration.seconds({props.get('timeout', 60)}),",
        f"            memory_size={props.get('memory', 256)},",
        f"            environment={env_str},",
        "            code=_lambda.Code.from_asset('lambda_code'),",
        "        )",
    ]


def _emit_api_gateway(node: ResourceNode, graph: ResourceGraph) -> list[str]:
    var = _var_name(node.id)
    lines = [
        f"        self.{var} = apigw.RestApi(",
        f"            self, '{node.id}',",
        f"            rest_api_name='{node.name}',",
        f"            description='{node.properties.get('description', '')}',",
        "        )",
    ]
    # Connect to Lambda targets
    for dep in graph.get_dependencies(node.id):
        if dep.type == ResourceType.LAMBDA:
            dep_var = _var_name(dep.id)
            lines.extend(
                [
                    f"        self.{var}.root.add_method(",
                    "            'POST',",
                    f"            apigw.LambdaIntegration(self.{dep_var}),",
                    "        )",
                ]
            )
    return lines


def _emit_sqs(node: ResourceNode, graph: ResourceGraph) -> list[str]:
    var = _var_name(node.id)
    lines = [
        f"        self.{var} = sqs.Queue(",
        f"            self, '{node.id}',",
        f"            queue_name='{node.name}',",
        f"            visibility_timeout=Duration.seconds({node.properties.get('visibility_timeout', 30)}),",
        "        )",
    ]
    # Connect as event source for Lambda
    for dep in graph.get_dependencies(node.id):
        if dep.type == ResourceType.LAMBDA:
            dep_var = _var_name(dep.id)
            lines.extend(
                [
                    f"        self.{dep_var}.add_event_source(",
                    f"            event_sources.SqsEventSource(self.{var}),",
                    "        )",
                ]
            )
    return lines


def _emit_eventbridge(node: ResourceNode, graph: ResourceGraph) -> list[str]:
    var = _var_name(node.id)
    schedule = node.properties.get("schedule_expression", "rate(1 hour)")
    lines = [
        f"        self.{var} = events.Rule(",
        f"            self, '{node.id}',",
        f"            schedule=events.Schedule.expression('{schedule}'),",
        "        )",
    ]
    for dep in graph.get_dependencies(node.id):
        if dep.type == ResourceType.LAMBDA:
            dep_var = _var_name(dep.id)
            lines.append(f"        self.{var}.add_target(targets.LambdaFunction(self.{dep_var}))")
    return lines


def _var_name(node_id: str) -> str:
    """Convert node ID to a Python variable name."""
    return node_id.replace("-", "_")
