"""CDK app entry point — synthesizable by `cdk synth`.

This module is auto-generated by `machete synth` and serves as the
CDK app that CloudFormation can deploy.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def write_cdk_app(cdk_source: str, output_dir: str = "cdk.out") -> Path:
    """Write a CDK app file to disk.

    Args:
        cdk_source: Python source code for the CDK app (from emit_cdk_app).
        output_dir: Directory to write the app to.

    Returns:
        Path to the generated app.py file.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    app_path = out / "app.py"
    app_path.write_text(cdk_source)

    return app_path


def write_cfn_template(template: dict, output_dir: str = "cdk.out") -> Path:
    """Write a CloudFormation template JSON to disk.

    Args:
        template: CloudFormation template dict (from emit_cdk_json).
        output_dir: Directory to write to.

    Returns:
        Path to the generated template.json file.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    template_path = out / "template.json"
    template_path.write_text(json.dumps(template, indent=2))

    return template_path
